### PR TITLE
Make Model-grid column editable to display validation messages.

### PR DESCRIPTION
**Pull request by deveres**
Grid editable don't process correctly validation. If validation error occur, it is not displayed. The new value is shown in field even it is not saved to DB. The validation messages is never shown.

My changes make grid editable to process correctly validation messages.

### CODE REVIEW

**Comment by z-song** [comment]
Very good job, thanks!

**Comment by deveres** [comment]
You welcome, waiting for merging. I need this fix.

**Comment by z-song** [comment]
@deveres I made a few suggestions, you can submit a commit based on them

**Comment by deveres** [comment]
Hi, I can't commit into master

**Comment by deveres** [comment]
I do not see your suggestions.

**Pull request closed without merging**
