### PR TITLE
select2 bug in hasmany field

### PR DESCRIPTION
**Pull request by mokadev**
select2 not fired because of misplaced $templateScript in hasmany field

### CODE REVIEW

**Comment by mokadev** [comment]
any chance to accept this pull request or at least can you tell how to use my own class to override the HasMany class ?

**Comment by z-song** [comment]
I have tried your change, but when add a new sub-form after click new button, none of these new fields works .

Do you have this problem?

**Comment by mokadev** [comment]
you're right! my bad. the fact is in my use case my change fix my problem.

I create 5 subform at page init and without this change none of this subform work :/

i'll figured out in a different way. thanks

**Comment by z-song** [comment]
You can show my your code and maybe I can help to find out.

**Comment by mokadev** [comment]
i was using this code to create 5 subform when i load the form (for create not for edit)

```
$script = <<<BOF
<script data-exec-on-popstate>
$(function () {
    var tpl = $('template.movements-tpl');
    for(i=1;i<=5;i++) {
        var template = tpl.html().replace(/\[_key_\]/g, '['+i+']');
        $('.has-many-movements-forms').append(template);
    }
});
</script>
BOF;

                $form->html($script);
```



i just forgot to trigger the select2 function 

with this code it's OK now 

```
$script = <<<BOF
<script data-exec-on-popstate>
$(function () {
    var tpl = $('template.movements-tpl');
    for(i=1;i<=5;i++) {
        var template = tpl.html().replace(/\[_key_\]/g, '['+i+']');
        $('.has-many-movements-forms').append(template);
    }
    
    $(".product_id").select2({
      ajax: {
        url: "/manager/api/products",
        dataType: 'json',
        delay: 250,
        data: function (params) {
          return {
            q: params.term,
            page: params.page
          };
        },
        processResults: function (data, params) {
          params.page = params.page || 1;
    
          return {
            results: data.data,
            pagination: {
              more: data.next_page_url
            }
          };
        },
        cache: true
      },
      minimumInputLength: 1,
      escapeMarkup: function (markup) {
          return markup;
      }
    });

});
</script>
BOF;

                $form->html($script);
```

It will be a cool feature to have a possibiliyy to init the form creation with some subform for exemple

```
$form->hasMany('movements', function (Form\NestedForm $form) {
                    $form->select('product_id')->options(function ($product_id) {
                        return Product::options($product_id);
                    })->ajax('/api/products')->required();

                    $form->decimal('qty', 'Mouvement')->required();

                })->initWith(5);
```

**Pull request closed without merging**
