### PR TITLE
Better SSL support, removed # fix #1768

### LINKED ISSUE #1768: 使用https反向代理表单提交出现http的情况。
- Laravel Version: 5.6 
- PHP Version: 7.1
- Laravel-admin: latest 

### Description:
后端服务是http服务，使用了https反向代理，admin.securty => true . 
也在AppserviceProvider里面URL::forceSchema("https") 了。
但是在Form -- Create 的时候 ， 获取Form action post地址的地方确是http://xxx.com/admin/resource
正确的应该是 https://www.com/admin/resource

src/Form.php
```   
 /**
     * Get current resource route url.
     *
     * @param int $slice
     *
     * @return string
     */
    public function resource($slice = -2)
    {
    // 这里是当前的 http://xxx.com/admin/resource , 应该吧http替换为是否设置了admin.securty的情况。麻烦处理下。谢谢。
        $segments = explode('/', trim(app('request')->getUri(), '/'));

        if ($slice != 0) {
            $segments = array_slice($segments, 0, $slice);
        }

        return implode('/', $segments);
    }
```

### PR DESCRIPTION
**Pull request by uacode**
Hello, for test, after merge clean project cache

### CODE REVIEW

**Comment by uacode** [comment]
Also merge plz into master

**Comment by z-song** [comment]
Thanks！

**Comment by uacode** [comment]
Can you cherry pick to master branch?)

Thanks!

**Comment by z-song** [comment]
@uacode already done, Thanks

**Pull request merged**
