### PR TITLE
Proposal: use Eloquent model instead of stdClass

### PR DESCRIPTION
**Pull request by slava-vishnyakov**
Imagine you have a model, like `Person`, this person has maybe something like `hasMany Phone` and `hasMany Email`, now you want to output in a grid `3 phones, 2 e-mails`

Currently it seems impossible, because:

```
$grid->column('phone')->display(function($v) {
    dd($this, $v);
});
```

Basically, 1) you can't write `'phone,email'`, 2) `$v$` is phone (but not email and 3) $this is `stdClass` with only phone

There are two benefits to make `$this` to `Eloquent` instead of `stdClass`:

1) you can write this:

```
$grid->column('info')->display(function() {
    return $this->phone->count() . " phones and " . $this->email->count() . " e-mails";
});
```

2) you can write a accessor on Eloquent, like this:
```
class Person {
  public function getPhoneInfoAttribute() {
    ..
  }
}

$grid->column('phone_info');
```

And due to the fact that Eloquent implements __get, this code (from tests) should still work:

```
$grid->column('column2_not_in_table')->display(function () {
    return $this->email.'#'.$this->profile['color'];
});
```

as well as this should work
```
$grid->column('column2_not_in_table')->display(function () {
    return $this->email.'#'.$this->profile->color;
});
```

The main problem is that in Model there is a call `$collection->toArray();` which makes all Eloquent models into `stdClass`, but if you call `all()` instead - you still get an array, but with Eloquent models.

### CODE REVIEW

**Comment by slava-vishnyakov** [comment]
The only problem I've discovered so far is this:

```php
$grid->column('phone.number');
$grid->column('phone_info')->display(function($v) {
    return $this->phone->number;
});
```

leads to this:

```php
ErrorException In Arr.php line 452 :

Indirect modification of overloaded element of App\Models\Person has no effect
```

Can't yet explain that.

**Comment by slava-vishnyakov** [comment]
Thought: maybe it would be better to create a method `displayEntity()` (like `display()`), which would receive Eloquent model...

**Comment by slava-vishnyakov** [comment]
Closing for now, need a better understanding.

**Comment by slava-vishnyakov** [comment]
Ok, I figured the problem now:
https://github.com/z-song/laravel-admin/pull/627/files#diff-a276aeaa84d596224cb1355666abf6a0R314

Since we have an Model instead of array now - we can't use array_set, we should use `$model->{$field} = $value`

**Comment by langeuh** [comment]
+1

**Comment by z-song** [comment]
@slava-vishnyakov 
I use another way to change display callback binding from stdClass to Eloquent model now

Ref  2577d2e

Thanks a lot for your proposal!

**Comment by slava-vishnyakov** [comment]
@z-song Thanks for the answer, though I don't understand the link to 2577d2e - how is the back button related?

**Comment by z-song** [comment]
Sorry, I copied the wrong commit,  see this commit 0faaaf1

**Comment by slava-vishnyakov** [comment]
Excellent! Thanks!

**Comment by slava-vishnyakov** [comment]
@z-song Strange, your version works slightly incorrect.

Basically, imagine having something like this `Post` hasMany `Comments`, each `Comment` hasMany `Authors`.

Now, we are displaying `Post`s on a grid and I want to display all `Author`s of all `Comment`s. I can't, because `$this->comments` is an `array`, not `Eloquent` instance (in my Pull Request it was `Eloquent` relation)

**Comment by z-song** [comment]
If you want to get `Eloquent relation`, use `$this->comments()` instead.

**Comment by slava-vishnyakov** [comment]
I didn't express my thoughts correctly, I don't need a `Relation` object, rather I need `name`s of all `Authors`, of each `Comment`.  Using `$this->comments()` I get a `HasMany` object, not the actual collection of `Comment`s (which is what I need). (What I need is `$this->comments`, but in my pull request - it's `Eloquent`, in your case - it's `array`)

Another example. Let's say you have `User`s, each of them hasOne `Phone`, then a `Phone` has `getFullNumberAttribute()` getter, which formats the number according to some rules. In my pull request, this works: `$this->phone->fullNumber` and this too: `$grid->column('phone.fullNumber');`, but in your case it doesn't work, because `phone` is an `array`, not `Eloquent` object.

**Comment by z-song** [comment]
I think I understand what you mean.

I reopened this pr,  but it didn't pass the tests.

**Comment by slava-vishnyakov** [comment]
Yeah, the weird part - at the moment I've sent PR - no tests were even run. I'll what's up with the tests.

**Comment by slava-vishnyakov** [comment]
Gets weirder and weirder. If I run only `testValueCallback` - it passes (and fails in Travis), even if I run whole `UserGridTest` - it works, but if I run the whole suite - the test `testValueCallback` fails. Weird...

**Comment by slava-vishnyakov** [comment]
Tests should pass if #699 is merged.

**Comment by langeuh** [comment]
@slava-vishnyakov do relations keep their Collection status? currently relations get turned into arrays which isn't really handy.

EG: currently this breaks, because `$this->comments` is an array and not a Collection of `OtherModel` 
Does this work in your code? Because that would be a massive improvement

```php
class Model{

    public function doSomethingWithComments(){
        return $this->comments->filter( function(){...} );
    }
    public function comments(){
        return $this->hasMany(OtherModel::class);
    }
}
```

```php
$grid->model()->with('comments');
$grid->nonExstingColum()->display(function(){
    return $this->doSomethingWithComments()->implode(',');
});
```

**Comment by slava-vishnyakov** [comment]
@langeuh Yes, relationships are not arrays in my pull request, which is what I describe here: https://github.com/z-song/laravel-admin/pull/627#issuecomment-290091292

**Comment by langeuh** [comment]
@z-song any news on this being merged? This would be a great addition! Or any news on the roadmap since it's been quit for some time now :)

**Comment by vladkucherov** [comment]
+1

**Pull request closed without merging**
