### PR TITLE
Fix - Switch submit wrong values

### PR DESCRIPTION
**Pull request by marzochi**
Switch isn't using entered values. Now it use entered values directly.

### CODE REVIEW

**Comment by marzochi** [comment]
Hi, this problem still continue. I define `value` properties for on/off states. But doesn't send these.. Only send `on` and `off` terms via http request. So result is fail, my column type is boolean on/off not valid for me.

```sql
SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'off' for column 'kapali' at row 1 (SQL: update `sinavlar` set `kapali` = off, `updated_at` = 2018-09-21 16:01:57 where `id` = 1)
```

```php
$states = [
    'on'  => ['value' => 1, 'text' => 'Evet', 'color' => 'danger'],
    'off' => ['value' => 0, 'text' => 'Hayır', 'color' => 'success'],
];
$grid->kapali("Kapalı")->switch($states);
```
@z-song please approve this fix :smile:

**Comment by zanemmm** [comment]
> notice: If set up a switch for a column the grid, then need to set the column in the form of the same switch.

You can see  http://laravel-admin.org/docs/#/en/model-grid-column?id=switch

Thanks, but it's not a bug that just send `on` of `off`. because you must set the same switch on the `form` function then `on` or `off` will be instead of real value.

This is a demo of `form` function. Just send `on` or `off` on frontend. It will be set `vip` or `other` when update. 

``` php
    protected function form()
    {
        $form = new Form(new Post);
        $states = [
            'on' => ['value' => 'vip', 'text' => '打开', 'color' => 'primary'],
            'off' => ['value' => 'other', 'text' => '关闭', 'color' => 'default'],
        ];
        $form->switch('level', 'level')->states($states);
    }
```
You can see the `SwitchField` class on `src/Form/Field/SwitchField.php` , line 31.

When `$value` is `on` return `$this->states[$value]['value'] // vip`. It's the reason will is not a bug.

``` php
public function prepare($value)
{
    if (isset($this->states[$value])) {
        return $this->states[$value]['value'];
    }

    return $value;
}
```

Sorry for my bad english. Thanks to your contribution.

**Comment by marzochi** [comment]
@zanemmm Thanks for reply. But I don't use this Switch in form. I used only in Grid, so I think need to change some codes..

**Comment by zanemmm** [comment]
@marzochi This code may help you :smile: , although it's not very beatiful.

```php
protected function form()
{
    $form->saving(function (Form $form) {
        $states = [
            'on' => 'vip',
            'off' => 'other',
        ];
        $key = $form->input('level');
        $form->model()->level = $states[$key];
    });
}
```

**Comment by marzochi** [comment]
Sorry, I'm using already in Form, but `src/Grid/Displayers/SwitchDisplay.php` and `src/Form/Field/SwitchField.php` different types.
Same codes works in Form. But not working in Grid 
Sorry for disturbing :smile:  @zanemmm 

Grid codes
```php
$states = [
    'on'  => ['value' => 1, 'text' => 'Evet', 'color' => 'danger'],
    'off' => ['value' => 0, 'text' => 'Hayır', 'color' => 'success'],
];
$grid->kapali("Kapalı")->switch($states);
```

Form codes
```php
$states = [
    'on'  => ['value' => 1, 'text' => 'Evet', 'color' => 'danger'],
    'off' => ['value' => 0, 'text' => 'Hayır', 'color' => 'success'],
];
$form->switch('kapali', 'Kapalı')->states($states);
```

**Pull request closed without merging**
