### PR TITLE
Fix failure click New and then Remove and Submit

### PR DESCRIPTION
**Pull request by miurabo**
In a form with hasMany, if you click on New and then click Remove, the array in the submitted data still exists, just set the value _remove_ to 1, which will result in a validate. Verification, resulting in failure to submit successfully

### CODE REVIEW

**Comment by z-song** [comment]
I can't reproduce your problem.

**Comment by miurabo** [comment]
I will check it

**Comment by KulwinderKohli** [comment]
I have updated to latest version but still I am having this issue. I am not able to remove existing data but able to add new data.

**Comment by KulwinderKohli** [comment]
> I have updated to latest version but still I am having this issue. I am not able to remove existing data but able to add new data.

I was using custom views. I noticed there is update in hasmany.blade.php file, I just replaced it with my custom view file. Working fine now.

**Comment by miurabo** [comment]
@KulwinderKohli 
Thank you
I might not have used the latest version

**Pull request closed without merging**
