### PR TITLE
add support for the MorphMany relation in the HasMany field component

### PR DESCRIPTION
**Pull request by langeuh**

### CODE REVIEW

**Comment by langeuh** [comment]
@z-song I switched to the 1.4 branch, but there seems to be something wrong with the tests and thus travis checks are failing for PR's

**Comment by z-song** [comment]
Laravel 5.4 uses `Dusk` as test framework,  all tests in `laravel-admin` need to overwrite with `Dusk`, but I didn't done this yet.

**Comment by langeuh** [comment]
You can still use the old testing method (i did that myself as well and took me 15 minutes)
https://laravel.com/docs/5.4/upgrade#upgrade-5.4.0 => see Testing.

Basically you need an extra package and extend your tests with another base testClass

**Comment by z-song** [comment]
These tests for 1.4 is ok now. Thanks!!

**Pull request merged**
