### PR TITLE
Add aggregation operation for total row: SUM, COUNT, AVG, MIN, MAX

### PR DESCRIPTION
**Pull request by sswm1975**
I suggest adding aggregate operations for total row: **SUM**, **COUNT**, **AVG**, **MIN**, **MAX**

Example use:
```
$grid->column('manager_name', 'Оператор')->totalRow('Всего:');
$grid->column('expand_orders', 'Заказы')->totalCount();
$grid->column('orders_all_sum', 'Сумма заказов')->totalSum();
$grid->column('orders_approved_avg', 'Cредний чек апрува')->totalAvg();
```

### CODE REVIEW

**Comment by fan153693** [comment]
想用这个功能，更新1.7.9版本时提示zhaob找不到
image

**Comment by sswm1975** [comment]
The methods totalCount, totalSum, totalMax, totalMin, totalAvg are not in release v1.7.9. They are proposed for a future release, if only Z-Song wants to add them through this pull requests.

**Review by ghost — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by sswm1975** [comment]
Good afternoon.  My variant of aggregate functions is not suitable for your package or do you have another implementation option?  Best regards, Sergei.

**Comment by matondojoao** [comment]
I can't use it please someone help me

**Pull request closed without merging**
