### PR TITLE
Fixed FA 5 dependencies for the new font awesome picker

### PR DESCRIPTION
**Pull request by robertwt7**
My last pull request was only for the font-awesome picker

Your font-awesome is still the old one and caused a lot of font missing

I updated the menu.blade.php without the prefix of fa every time adding item['icon'] because it breaks in FA 5, with the fontawesome picker it includes all of the prefix of the new FA 5 (fas, fab, etc).

I also updated each default font with the correct classes

Checked and test, love your work btw

Thanks!

### CODE REVIEW

**Comment by vlados** [comment]
Great!! Waiting for the release

**Comment by Bluefitdev** [comment]
This should be alright, I have this updated on my local too

**Comment by z-song** [comment]
Thanks！

**Comment by muhlisabdi** [comment]
Laravel admin using admin lte 2.3. its rely on font awesome 4. Some font will missing instead you change all font awesome class style

**Comment by z-song** [comment]
> Laravel admin using admin lte 2.3. its rely on font awesome 4. Some font will missing instead you change all font awesome class style

@muhlisabdi Yes, you'r right，some font styles are missing, and all extensions using font-awesome 4 need to be updated, which brings more problems, I will revert this pull request

**Comment by afwn90cj93201nixr2e1re** [comment]
@z-song reverting is not solution, you should not depend on old stuff, they should just update what they want as they want, here's nothing was missed, just renamed some icos and separated to another packs.

**Comment by robertwt7** [comment]
True.. I think we're just missing a bit here and there! We can help fix, such as the toggle icon and some missing stuff

**Pull request merged**
