### PR TITLE
Make relation in detail view support quickcreate

### PR DESCRIPTION
**Pull request by parse-dinghua**
在详情页面的关联关系里，也可以使用快捷创建。

image

### CODE REVIEW

**Comment by parse-dinghua** [comment]
Anybody maintain the pr? @z-song

**Comment by Superoryco** [comment]
This is exactly what we need when using QuickCreate in a nested grid, @z-song please merge this in the next update. Thank you!

**Comment by Superoryco** [comment]
@parse-dinghua Do you have any workarounds?

**Comment by parse-dinghua** [comment]
> @parse-dinghua Do you have any workarounds?

Move whole laravel-admin to local packages, but not recommended.

**Pull request closed without merging**
