### PR TITLE
Allow use of laravel-admin in subfolders

### PR DESCRIPTION
**Pull request by shemgp**
It would be nice if your great admin panel could be used in subfolders (eg. http://localhost/~shemgp/laravel-admin/).  This patch will allow this (on the things I tested, at least).

### CODE REVIEW

**Comment by z-song** [comment]
If you want to access admin panel with url `http://localhost/~shemgp/laravel-admin/)`,  just set `route.prefix` to `~shemgp/laravel-admin` in `config/admin.php`

**Comment by shemgp** [comment]
If I do that, then `http://localhost/~shemgp/laravel-admin/admin` displays `Sorry, the page you are looking for could not be found.`.

**Comment by z-song** [comment]
Set prefix to `~shemgp/laravel-admin/admin`

**Comment by shemgp** [comment]
In my testing machine with `config/admin.php`:
```php
        'prefix' => '~shemgp/tests/laravel/zsonglaraveladmin/admin',
```
accessing `http://localhost/~shemgp/tests/laravel/zsonglaraveladmin/admin` returns `404` or `Sorry, the page you are looking for could not be found.`.

**Comment by z-song** [comment]
@shemgp what's the root path?

**Comment by shemgp** [comment]
In my instance, most of the Laravel code is in `/home/shemgp/src/tests/laravel/zsonglaraveladmin` except that the `public` folder is a symlink to `/home/shemgp/public_html/tests/laravel/zsonglaraveladmin` with its `index.php` having:
```php
require '/home/shemgp/src/tests/laravel/zsonglaraveladmin/vendor/autoload.php';
$app = require_once '/home/shemgp/src/tests/laravel/zsonglaraveladmin/bootstrap/app.php';
```
So in the browser, I access it through `http://localhost/~shemgp/tests/laravel/zsonglaraveladmin/` and the admin through `http://localhost/~shemgp/tests/laravel/zsonglaraveladmin/admin`.

In `.env`:
```ini
APP_URL=http://localhost/~shemgp/tests/laravel/zsonglaraveladmin
```
or
```ini
APP_URL=http://localhost/
```
both doesn't work.

**Pull request closed without merging**
