### PR TITLE
Update admin.php

### PR DESCRIPTION
**Pull request by jxlwqq**
get secure's value from env file

### CODE REVIEW

**Comment by jxlwqq** [comment]
很多时候，本地开发环境是 http，而生产环境是 https。

**Comment by artem-tverdokhlebov** [comment]
Maybe you need to prepend env variable name like "ADMIN_SECURE"?

**Comment by jxlwqq** [comment]
@z-song @artem-tverdokhlebov  I think, `APP_ENCRYPT` is better, The word `SECURE` is very ambiguous.

**Comment by artem-tverdokhlebov** [comment]
@jxlwqq this variable applies only to admin panel, why would you choose word "APP"?
And "ENCRYPT" means that it's encrypted, while "SECURE" means "secured". I think "SECURE" is better, also this word is used in config file already.

**Comment by jxlwqq** [comment]
@artem-tverdokhlebov `https://` is for the whole `APP`, not only for the `ADMIN` module, and `SECURE` contains too much meaning.

**Comment by z-song** [comment]
@jxlwqq @artem-tverdokhlebov How about using the word `https` directly? and `ADMIN_HTTPS` in .env

**Comment by artem-tverdokhlebov** [comment]
@z-song @jxlwqq I think that `ADMIN_HTTPS` variant is the best

**Pull request merged**
